#!/usr/bin/env python3
"""
mksprite - Convert a PNG image into an N64 Sprite .inc.h file.

Usage:
    mksprite.py <input.png> -f <format> --tile-width <W> --tile-height <H>
                --name <sprite_name> --dl <dl_name> -o <output.inc.h>

Produces a single .inc.h file containing:
  - Pixel data arrays for each tile (via pigment64 --c-array --word-swap)
  - Palette data (for CI formats)
  - Bitmap struct array
  - Display list declaration
  - Sprite struct
"""

import argparse
import math
import subprocess
import sys
import tempfile
from pathlib import Path

import png


FORMAT_INFO = {
    "rgba16": {"bpp": 2, "c_type": "unsigned short", "gbi_fmt": "G_IM_FMT_RGBA", "gbi_siz": "G_IM_SIZ_16b"},
    "rgba32": {"bpp": 4, "c_type": "unsigned short", "gbi_fmt": "G_IM_FMT_RGBA", "gbi_siz": "G_IM_SIZ_32b"},
    "i8":     {"bpp": 1, "c_type": "unsigned char",  "gbi_fmt": "G_IM_FMT_I",    "gbi_siz": "G_IM_SIZ_8b"},
    "ia16":   {"bpp": 2, "c_type": "unsigned short", "gbi_fmt": "G_IM_FMT_IA",   "gbi_siz": "G_IM_SIZ_16b"},
    "ci8":    {"bpp": 1, "c_type": "unsigned char",  "gbi_fmt": "G_IM_FMT_CI",   "gbi_siz": "G_IM_SIZ_8b"},
}


def crop_png(src_path: Path, dst_path: Path, x: int, y: int, w: int, h: int):
    """Crop a region from a PNG and write it to dst_path."""
    reader = png.Reader(filename=str(src_path))
    img_w, img_h, rows, info = reader.read()

    planes = info.get("planes", 3)
    has_alpha = info.get("alpha", False)
    greyscale = info.get("greyscale", False)
    palette = info.get("palette")
    bitdepth = info.get("bitdepth", 8)

    all_rows = list(rows)

    cropped_rows = []
    for row_idx in range(y, min(y + h, img_h)):
        row = all_rows[row_idx]
        if palette:
            cropped_rows.append(row[x : x + w])
        else:
            cropped_rows.append(row[x * planes : (x + w) * planes])

    writer_kwargs = {
        "width": w,
        "height": len(cropped_rows),
        "bitdepth": bitdepth,
        "greyscale": greyscale,
        "alpha": has_alpha,
    }
    if palette:
        writer_kwargs["palette"] = palette
        writer_kwargs["greyscale"] = False
        writer_kwargs["alpha"] = False

    writer = png.Writer(**writer_kwargs)
    with open(dst_path, "wb") as f:
        writer.write(f, cropped_rows)


def pigment64_to_c_array(png_path: Path, fmt: str) -> str:
    """Run pigment64 to convert a PNG tile to a C array string."""
    result = subprocess.run(
        ["pigment64", "to-bin", "-f", fmt, "--word-swap", "--c-array", str(png_path)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"pigment64 error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def pigment64_palette(png_path: Path) -> str:
    """Extract palette from a CI PNG as a C array."""
    result = subprocess.run(
        ["pigment64", "to-bin", "-f", "palette", "--c-array", str(png_path)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"pigment64 palette error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout


def main():
    parser = argparse.ArgumentParser(description="Convert PNG to N64 Sprite .inc.h")
    parser.add_argument("input", type=Path, help="Input PNG file")
    parser.add_argument("-f", "--format", required=True, choices=FORMAT_INFO.keys())
    parser.add_argument("--tile-width", type=int, required=True)
    parser.add_argument("--tile-height", type=int, required=True)
    parser.add_argument("--name", required=True, help="Sprite variable name")
    parser.add_argument("--dl", required=True, help="Display list variable name")
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args()

    fmt_info = FORMAT_INFO[args.format]
    is_ci = args.format.startswith("ci")

    # Read input image dimensions
    reader = png.Reader(filename=str(args.input))
    img_w, img_h, _, _ = reader.read()

    tile_w = args.tile_width
    tile_h = args.tile_height
    cols = math.ceil(img_w / tile_w)
    rows = math.ceil(img_h / tile_h)

    out_lines = []
    out_lines.append(f"/* Generated by mksprite from {args.input.name} */")
    out_lines.append("")
    out_lines.append("#include <PR/sp.h>")
    out_lines.append("")

    # For CI formats, extract palette from the full image first
    if is_ci:
        with tempfile.TemporaryDirectory() as tmpdir:
            pal_data = pigment64_palette(args.input)
            out_lines.append(f"static unsigned short {args.name}_pal[] = {{")
            out_lines.append(pal_data)
            out_lines.append("};")
            out_lines.append("")

    # Slice image into tiles and convert each
    tile_names = []
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        for row in range(rows):
            for col in range(cols):
                x = col * tile_w
                y = row * tile_h
                actual_w = min(tile_w, img_w - x)
                actual_h = min(tile_h, img_h - y)

                tile_name = f"{args.name}_bm{row}_{col}"
                tile_names.append((tile_name, actual_w, actual_h))

                tile_png = tmpdir / f"{tile_name}.png"
                crop_png(args.input, tile_png, x, y, actual_w, actual_h)

                c_array = pigment64_to_c_array(tile_png, args.format)

                out_lines.append(f"static {fmt_info['c_type']} {tile_name}[] = {{")
                out_lines.append(c_array)
                out_lines.append("};")
                out_lines.append("")

    # Bitmap struct array
    out_lines.append(f"Bitmap {args.name}_bitmaps[] = {{")
    for tile_name, actual_w, actual_h in tile_names:
        # Bitmap fields: { width, width_img, s, t, buf, actual_height, lut_offset }
        # width_img is the padded width (next power of 2 or TMEM-aligned)
        out_lines.append(f"    {{ {actual_w}, {actual_w}, 0, 0, (u8*){tile_name}, {actual_h}, 0 }},")
    out_lines.append("};")
    out_lines.append("")

    nbitmaps = len(tile_names)
    out_lines.append(f"#define NUM_{args.name}_BMS  (sizeof({args.name}_bitmaps) / sizeof(Bitmap))")
    out_lines.append("")

    # Display list
    if args.dl != "NULL" and args.dl != "D_00000000":
        out_lines.append(f"extern Gfx {args.dl}[];")
        out_lines.append("")
        dl_ref = args.dl
    else:
        dl_ref = "NULL"

    # Sprite struct
    # Determine physical tile height (bmHreal) - usually same as tile_h or padded
    bmHreal = tile_h

    lut_line = f"0, 0, NULL" if not is_ci else f"0, 256, (u8*){args.name}_pal"

    out_lines.append(f"Sprite {args.name} = {{")
    out_lines.append(f"    0, 0,                          /* Position: x, y */")
    out_lines.append(f"    {img_w - 1}, {img_h - 1},                      /* Sprite size in texels (x, y) */")
    out_lines.append(f"    1.0, 1.0,                      /* Sprite Scale: x, y */")
    out_lines.append(f"    0, 0,                          /* Sprite Explosion Spacing: x, y */")
    out_lines.append(f"    SP_TEXSHUF | SP_Z | SP_OVERLAP, /* Sprite Attributes */")
    out_lines.append(f"    0x1234,                        /* Sprite Depth: Z */")
    out_lines.append(f"    255, 255, 255, 255,            /* Sprite Coloration: RGBA */")
    out_lines.append(f"    {lut_line},  /* CLUT: start, length, address */")
    out_lines.append(f"    0, 1,                          /* Bitmap index: start, step */")
    out_lines.append(f"    NUM_{args.name}_BMS,              /* Number of bitmaps */")
    out_lines.append(f"    NUM_DL(NUM_{args.name}_BMS),      /* Number of display list locations */")
    out_lines.append(f"    {tile_h}, {bmHreal},                      /* Bitmap Height: used, physical */")
    out_lines.append(f"    {fmt_info['gbi_fmt']},             /* Bitmap Format */")
    out_lines.append(f"    {fmt_info['gbi_siz']},            /* Bitmap Texel Size */")
    out_lines.append(f"    {args.name}_bitmaps,              /* Pointer to bitmaps */")
    out_lines.append(f"    {dl_ref},                        /* Display list memory */")
    out_lines.append(f"    NULL                           /* next_dl pointer */")
    out_lines.append(f"}};")
    out_lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        f.write("\n".join(out_lines))

    print(f"Generated {args.output} ({nbitmaps} tiles, {img_w}x{img_h}, {args.format})")


if __name__ == "__main__":
    main()
