name: Build

on:
  push:
  pull_request:

jobs:
  build:
    # This is a *private* build container.
    container: ghcr.io/ethteck/pokemonsnap-build:main

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - us

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          apt-get install -y binutils-mips-linux-gnu ninja-build

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache pigment64
        id: cache-pigment64
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/pigment64
          key: pigment64-${{ runner.os }}

      - name: Install pigment64
        if: steps.cache-pigment64.outputs.cache-hit != 'true'
        run: cargo install pigment64

      - name: Get the dependency
        run: cp /orig/* .

      - name: Setup
        run: |
          uv run ./configure.py --setup
          uv run ./configure.py

      - name: Build
        run: bash -o pipefail -c 'ninja 2>&1 | tee build_log.txt'

      - name: Upload build_log artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.version }}_build_log
          path: build_log.txt

      - name: Generate objdiff report
        run: |
          uv run mapfile_parser objdiff_report report.json --version ${{ matrix.version }}

      - name: Upload progress report artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.version }}_report
          path: report.json
